### ISSUE TITLE
关于模拟登陆

### ISSUE THREAD

**Issue by idootop** [CodingDogzxg/grabbing-dog#1]
楼主应该知道强智教务系统有两个登录入口的吧
一个需要重写js的登录逻辑，另一个直接拼接登录信息就好，
看了下代码，其实楼主都有解决，nice。
重定向的问题其实使用reques post登录信息之后会自动重定向的登录成功的页面，
直接判断一下获取到的页面信息就可以判断是否登录成功，
以上，就酱。

**Comment by CodingDogzxg** [comment]
emmm 已经写好了 在另一个版本里 重定向的问题是因为验证码和主页面没有绑定好... 这个坑算是填完了 因为嫌弃pyinstaller打包的exe太臃肿 最近在写python-embedded版本 写的也差不多啦 在没有python环境下也可以运行.py了 哈哈 居然有人看我的代码 很开心 谢谢您
